image: node:12.10.0-alpine

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules

build:
  stage: build
  script:
    - npm install
  only:
    - master
    - develop

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - coverage/
  only:
    - master
    - develop

pages:
  stage: deploy
  script:
    - mv build/ public/
  artifacts:
    paths:
      - public
  only:
    - master
