image: node:14.12.0-alpine

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - master
    - develop

test:
  stage: test
  script:
    - test -f "build/index.html"
  only:
    - master
    - develop

pages:
  stage: deploy
  script:
    - rm public/
    - mv build/ public/
    - ls public/
  artifacts:
    paths:
      - public/
  only:
    - master
