image: node:12.10.0-alpine

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - master
    - develop

test:
  stage: test
  script:
    - test -f "build/index.html"
    - npm run test
  artifacts:
    paths:
      - coverage/
  only:
    - master
    - develop

pages:
  stage: deploy
  script:
    - mv build/ public/
    - ls -la public/
  artifacts:
    paths:
      - public/
  only:
    - master
