image: node:12.10.0-alpine

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  only:
    - master
    - develop

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - coverage
  only:
    - master
    - develop

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv build/ public/
  artifacts:
    paths:
      - public
  only:
    - master
